// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $_middleware from "./routes/_middleware.ts";
import * as $api_login from "./routes/api/login.ts";
import * as $api_logout from "./routes/api/logout.ts";
import * as $api_machine_id_id_ from "./routes/api/machine/id/[id].ts";
import * as $api_machine_index from "./routes/api/machine/index.ts";
import * as $api_machine_macaddr_id_ from "./routes/api/machine/macaddr/[id].ts";
import * as $index from "./routes/index.tsx";
import * as $login from "./routes/login.tsx";

import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
    "./routes/_middleware.ts": $_middleware,
    "./routes/api/login.ts": $api_login,
    "./routes/api/logout.ts": $api_logout,
    "./routes/api/machine/id/[id].ts": $api_machine_id_id_,
    "./routes/api/machine/index.ts": $api_machine_index,
    "./routes/api/machine/macaddr/[id].ts": $api_machine_macaddr_id_,
    "./routes/index.tsx": $index,
    "./routes/login.tsx": $login,
  },
  islands: {},
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
